
services:
  chatgpt: # TF_VAR_CHATGPT_NAME
    image: ${TF_DOMAIN}/${TF_VAR_CHATGPT_NAME}:${TF_VAR_VERSION_DOCKER_OLLAMA}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_CHATGPT_NAME}/image/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_OLLAMA}
    container_name: ${TF_VAR_CHATGPT_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_CHATGPT_PORT_EXT}:${TF_VAR_CHATGPT_PORT_INT}
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:${TF_VAR_CHATGPT_PORT_INT}"]
      start_period: 4m
      interval: 45s
      timeout: 30s
      retries: 5