protocol: "http"
#https_config:
#  cert: "server.crt"
#  key: "server.key"
port: 8080
worker_pool:
  workers: 10
  backend: "redis"
  redis_pool:
    #redis://[arbitrary_username:password@]ipaddress:port/database_index
    redis_url: redis://harbor-redis:6379/2
    namespace: "harbor_job_service_namespace"
job_loggers:
  - name: "STD_OUTPUT"
    level: "INFO"
  - name: "FILE"
    level: "INFO"
    settings:
      base_dir: "/var/log/jobs"
    sweeper:
      duration: 1
      settings:
        work_dir: "/var/log/jobs"
loggers:
  - name: "STD_OUTPUT"
    level: "INFO"
admin_server: "http://adminserver:8080/"
