version: '3.9'

services:
  postgres: # TF_VAR_POSTGRES_NAME
    image: ${TF_VAR_DOMAIN}/${TF_VAR_POSTGRES_NAME}:${TF_VAR_VERSION_DOCKER_POSTGRES}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_POSTGRES_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_POSTGRES}
    container_name: ${TF_VAR_POSTGRES_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_POSTGRES_NAME}:/var/lib/postgresql/data
    # ports:
    #   - ${TF_VAR_POSTGRES_PORT_EXT}:${TF_VAR_POSTGRES_PORT_INT}
    environment:
      POSTGRES_USER: ${TF_VAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TF_VAR_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TF_VAR_POSTGRES_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5