version: '3.9'

services:
  elasticsearch: # TF_VAR_ELASTICSEARCH_NAME
    image: ${TF_VAR_DOMAIN}/${TF_VAR_ELASTICSEARCH_NAME}:${TF_VAR_VERSION_DOCKER_ELASTICSEARCH}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_ELASTICSEARCH_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_ELASTICSEARCH}
    container_name: ${TF_VAR_ELASTICSEARCH_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_ELASTICSEARCH_NAME}:/usr/share/elasticsearch/data
    # ports:
    #   - ${TF_VAR_ELASTICSEARCH_PORT_EXT}:${TF_VAR_ELASTICSEARCH_PORT_INT}
    environment:
      # - ELASTIC_USERNAME=${TF_VAR_ELASTICSEARCH_USER}
      # - ELASTIC_PASSWORD=${TF_VAR_ELASTICSEARCH_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=${TF_VAR_ELASTICSEARCH_NAME}
      - discovery.type=single-node

      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.security.transport.ssl.enabled=false

      # - xpack.security.http.ssl.enabled=true
      # - xpack.security.http.ssl.certificate="http-spikyspam.site.crt"
      # - xpack.security.http.ssl.key="http-spikyspam.site.key"

      - http.cors.enabled=true
      - http.cors.allow-origin="*"
