version: '3.8'

services:
  elasticsearch: # TF_VAR_ELASTICSEARCH_NAME
    image: elasticsearch:${TF_VAR_VERSION_DOCKER_ELASTICSEARCH}
    container_name: ${TF_VAR_ELASTICSEARCH_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_ELASTICSEARCH_NAME}:/usr/share/elasticsearch/data
    # ports:
    #   - ${TF_VAR_ELASTICSEARCH_PORT_EXT}:${TF_VAR_ELASTICSEARCH_PORT_INT}
    environment:
      # - ELASTIC_USERNAME=${TF_VAR_ELASTICSEARCH_USER}
      # - ELASTIC_PASSWORD=${TF_VAR_ELASTICSEARCH_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=${TF_VAR_ELASTICSEARCH_NAME}
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.enrollment.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
