ARG VERSION
FROM ubuntu:${VERSION}

RUN apt-get update && apt-get upgrade -y
RUN apt-get install sudo git curl wget iptables gnupg2 nmap python3 python3-pip hping3 build-essential ruby-dev libpcap-dev libgmp3-dev php testdisk dnsmasq hostapd net-tools sshpass netcat-traditional netcat-openbsd -y
RUN apt-get install python3-tabulate python3-terminaltables python3-tld python3-requests python3-requests-file python3-jsbeautifier python3-lxml python3-prettytable -y

