version: '3.9'

services:
  ollama: # ${TF_VAR_OLLAMA_NAME}
    image: ${TF_VAR_DOMAIN}/${TF_VAR_OLLAMA_NAME}:${TF_VAR_VERSION_DOCKER_OLLAMA}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_OLLAMA_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_OLLAMA}
    container_name: ${TF_VAR_OLLAMA_NAME}
    restart: unless-stopped
