
services:
  harbor-postgres: # ${TF_VAR_HARBOR_NAME}-${TF_VAR_POSTGRES_NAME}
    extends:
      service: ${TF_VAR_POSTGRES_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_POSTGRES_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_HARBOR_NAME}-${TF_VAR_POSTGRES_NAME}
    volumes:
      - $HOME/docker/${TF_VAR_HARBOR_NAME}/${TF_VAR_POSTGRES_NAME}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${TF_VAR_HARBOR_NAME}

  harbor-redis: # ${TF_VAR_HARBOR_NAME}-${TF_VAR_REDIS_NAME}
    extends:
      service: ${TF_VAR_REDIS_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_REDIS_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_HARBOR_NAME}-${TF_VAR_REDIS_NAME}
    volumes:
      - $HOME/docker/${TF_VAR_HARBOR_NAME}/${TF_VAR_REDIS_NAME}:/data

  harbor-registry: # ${TF_VAR_HARBOR_NAME}-registry
    image: ${TF_VAR_DOMAIN}/${TF_VAR_HARBOR_NAME}-registry:${TF_VAR_VERSION_DOCKER_HARBOR}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/dockerfile_registry
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_HARBOR}
    container_name: ${TF_VAR_HARBOR_NAME}-registry
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_HARBOR_NAME}/registry:/storage
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/config/registry/:/etc/registry/:ro
    environment:
      - REGISTRY_HTTP_SECRET=${TF_VAR_HARBOR_HTTP_SECRET}

  harbor-registryctl: # ${TF_VAR_HARBOR_NAME}-registryctl
    image: ${TF_VAR_DOMAIN}/${TF_VAR_HARBOR_NAME}-registryctl:${TF_VAR_VERSION_DOCKER_HARBOR}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/dockerfile_registryctl
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_HARBOR}
    container_name: ${TF_VAR_HARBOR_NAME}-registryctl
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_HARBOR_NAME}/registry:/storage
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/config/registry/:/etc/registry/:ro
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/config/registryctl/config.yml:/etc/registryctl/config.yml:ro
    environment:
      - CORE_SECRET=${TF_VAR_HARBOR_CORE_SECRET}
      - JOBSERVICE_SECRET=${TF_VAR_HARBOR_JOBSERVICE_SECRET}
      - REGISTRY_HTTP_SECRET=${TF_VAR_HARBOR_HTTP_SECRET}

  harbor-core: # ${TF_VAR_HARBOR_NAME}-core
    depends_on:
      - ${TF_VAR_HARBOR_NAME}-registry
    image: ${TF_VAR_DOMAIN}/${TF_VAR_HARBOR_NAME}-core:${TF_VAR_VERSION_DOCKER_HARBOR}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/dockerfile_core
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_HARBOR}
    container_name: ${TF_VAR_HARBOR_NAME}-core
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_HARBOR_NAME}/core:/data
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/config/core/app.conf:/etc/core/app.conf:ro
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/config/core/private_key.pem:/etc/core/private_key.pem:ro
    environment:
      - CORE_KEY=${TF_VAR_HARBOR_CORE_SECRET}
      - _REDIS_URL_CORE=redis://${TF_VAR_HARBOR_NAME}-${TF_VAR_REDIS_NAME}:6379/0
      - SYNC_REGISTRY=false
      - CHART_CACHE_DRIVER=redis
      - _REDIS_URL_REG=redis://${TF_VAR_HARBOR_NAME}-${TF_VAR_REDIS_NAME}:6379/1
      - PORT=${TF_VAR_HARBOR_PORT_INT}
      - LOG_LEVEL=info
      - EXT_ENDPOINT=http://${TF_VAR_HARBOR_NAME}.${TF_VAR_DOMAIN}
      - DATABASE_TYPE=postgresql
      - REGISTRY_CONTROLLER_URL=http://${TF_VAR_HARBOR_NAME}-registryctl:${TF_VAR_HARBOR_PORT_INT}
      - POSTGRESQL_HOST=${TF_VAR_HARBOR_NAME}-${TF_VAR_POSTGRES_NAME}
      - POSTGRESQL_PORT=${TF_VAR_POSTGRES_PORT_INT}
      - POSTGRESQL_DATABASE=${TF_VAR_HARBOR_NAME}
      - POSTGRESQL_USERNAME=${TF_VAR_POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${TF_VAR_POSTGRES_PASSWORD}
      - POSTGRESQL_SSLMODE=disable
      - REGISTRY_URL=http://${TF_VAR_HARBOR_NAME}-registry:${TF_VAR_HARBOR_PORT_INT_REGISTRY}
      - TOKEN_SERVICE_URL=http://${TF_VAR_HARBOR_NAME}-core:${TF_VAR_HARBOR_PORT_INT}/service/token
      - HARBOR_ADMIN_PASSWORD=${TF_VAR_HARBOR_PASSWORD}
      - CORE_SECRET=${TF_VAR_HARBOR_CORE_SECRET}
      - JOBSERVICE_SECRET=${TF_VAR_HARBOR_JOBSERVICE_SECRET}
      - ADMIRAL_URL=
      - CORE_URL=http://${TF_VAR_HARBOR_NAME}-core:${TF_VAR_HARBOR_PORT_INT}
      - JOBSERVICE_URL=http://${TF_VAR_HARBOR_NAME}-jobservice:${TF_VAR_HARBOR_PORT_INT}
      - REGISTRY_STORAGE_PROVIDER_NAME=filesystem
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=harbor_registry_password
      - READ_ONLY=false
      - RELOAD_KEY=

  harbor-portal: # ${TF_VAR_HARBOR_NAME}-portal
    depends_on:
      - ${TF_VAR_HARBOR_NAME}-core
    image: ${TF_VAR_DOMAIN}/${TF_VAR_HARBOR_NAME}-portal:${TF_VAR_VERSION_DOCKER_HARBOR}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/dockerfile_portal
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_HARBOR}
    container_name: ${TF_VAR_HARBOR_NAME}-portal
    restart: unless-stopped

  harbor-jobservice: # ${TF_VAR_HARBOR_NAME}-jobservice
    depends_on:
      - ${TF_VAR_HARBOR_NAME}-${TF_VAR_REDIS_NAME}
      - ${TF_VAR_HARBOR_NAME}-core
    image: ${TF_VAR_DOMAIN}/${TF_VAR_HARBOR_NAME}-jobservice:${TF_VAR_VERSION_DOCKER_HARBOR}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/dockerfile_jobservice
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_HARBOR}
    container_name: ${TF_VAR_HARBOR_NAME}-jobservice
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_HARBOR_NAME}/jobservice:/var/log/jobs
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/config/jobservice/config.yml:/etc/jobservice/config.yml:ro
    environment:
      - CORE_SECRET=${TF_VAR_HARBOR_CORE_SECRET}
      - JOBSERVICE_SECRET=${TF_VAR_HARBOR_JOBSERVICE_SECRET}
      - CORE_URL=http://${TF_VAR_HARBOR_NAME}-core:${TF_VAR_HARBOR_PORT_INT}
      - REGISTRY_CONTROLLER_URL=http://${TF_VAR_HARBOR_NAME}-registryctl:${TF_VAR_HARBOR_PORT_INT}
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=harbor_registry_password

  harbor-nginx: # ${TF_VAR_HARBOR_NAME}-nginx
    depends_on:
      - ${TF_VAR_HARBOR_NAME}-${TF_VAR_POSTGRES_NAME}
      - ${TF_VAR_HARBOR_NAME}-registry
      - ${TF_VAR_HARBOR_NAME}-core
      - ${TF_VAR_HARBOR_NAME}-portal
    image: ${TF_VAR_DOMAIN}/${TF_VAR_HARBOR_NAME}-nginx:${TF_VAR_VERSION_DOCKER_NGINX}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/dockerfile_nginx
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_NGINX}
    container_name: ${TF_VAR_HARBOR_NAME}-nginx
    restart: unless-stopped
    volumes:
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/config/proxy/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    ports:
      - ${TF_VAR_HARBOR_PORT_EXT}:${TF_VAR_HARBOR_PORT_INT}
