version: "3.8"

services:
  pihole: # ${TF_VAR_PIHOLE_NAME}
    image: pihole/pihole:${TF_VAR_VERSION_DOCKER_PIHOLE}
    container_name: ${TF_VAR_PIHOLE_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_PIHOLE_NAME}/data:/etc/pihole
      - $HOME/docker/${TF_VAR_PIHOLE_NAME}/dnsmasq:/etc/dnsmasq.d
    ports:
      - "${TF_VAR_PIHOLE_PORT_EXT_DNS}:${TF_VAR_PIHOLE_PORT_INT_DNS}/tcp"
      - "${TF_VAR_PIHOLE_PORT_EXT_DNS}:${TF_VAR_PIHOLE_PORT_INT_DNS}/udp"
      - "${TF_VAR_PIHOLE_PORT_EXT_DHCP}:${TF_VAR_PIHOLE_PORT_INT_DHCP}/udp"
      - "${TF_VAR_PIHOLE_PORT_EXT_HTTP}:${TF_VAR_VAULTWARDEN_PORT_INT}/tcp"
    environment:
      TZ: ${TF_VAR_PIHOLE_TZ}
      WEBPASSWORD: ${TF_VAR_PIHOLE_PASSWORD}
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
