version: '3.8'

services:
  gitlab: # ${TF_VAR_GITLAB_NAME}
    image: gitlab/gitlab-ce:${TF_VAR_VERSION_DOCKER_GITLAB}
    container_name: ${TF_VAR_GITLAB_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_GITLAB_PORT_EXT_80}:${TF_VAR_GITLAB_PORT_INT_80}
      - ${TF_VAR_GITLAB_PORT_EXT_443}:${TF_VAR_GITLAB_PORT_INT_443}
      - ${TF_VAR_GITLAB_PORT_EXT_22}:${TF_VAR_GITLAB_PORT_INT_22}
    volumes:
      - $HOME/docker/${TF_VAR_GITLAB_NAME}/config:/etc/gitlab
      - $HOME/docker/${TF_VAR_GITLAB_NAME}/logs:/var/log/gitlab
      - $HOME/docker/${TF_VAR_GITLAB_NAME}/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${TF_VAR_GITLAB_NAME}.${TF_VAR_DOMAIN}'
    hostname: ${TF_VAR_GITLAB_NAME}.${TF_VAR_DOMAIN}
    shm_size: '256m'
    networks:
      - ${TF_VAR_GITLAB_NAME}

  gitlab-runner: # ${TF_VAR_GITLAB_NAME}-runner
    depends_on:
      - ${TF_VAR_GITLAB_NAME}
    image: gitlab/gitlab-runner:alpine3.18
    container_name: ${TF_VAR_GITLAB_NAME}-runner
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_GITLAB_NAME}/run/docker.sock:/var/run/docker.sock
      - $HOME/docker/${TF_VAR_GITLAB_NAME}/gitlab-runner:/etc/gitlab-runner
    networks:
      - ${TF_VAR_GITLAB_NAME}

networks:
  gitlab: # ${TF_VAR_GITLAB_NAME}
    name: ${TF_VAR_GITLAB_NAME}
    driver: bridge
