FROM ruby:3.2.1-bullseye

RUN apt-get update && apt-get install sudo -y && \
    git clone https://github.com/beefproject/beef

WORKDIR /beef

ENV GITACTIONS no
ENV TERM xterm
RUN /bin/bash -c "yes | ./install"

# ENV BEEF_WAITTIME=0 \
#     BEEF_DEBUG=false \
#     BEEF_USER=${TF_VAR_DOCKER_BEEF_USER} \
#     BEEF_PASSWORD=${TF_VAR_DOCKER_BEEF_PASSWORD} \
#     BEEF_SSL=false \
#     BEEF_PUBLIC_IP=beef.${TF_VAR_DOMAIN} \
#     BEEF_PUBLIC_PORT=${TF_VAR_DOCKER_BEEF_PORT} \
#     BEEF_SSL_PUBLIC=false \
#     BEEF_MSF_ENABLE="false" \
#     MSF_RPC_HOST="0.0.0.0" \
#     MSF_RPC_PORT="55553" \
#     MSF_RPC_USER="msfuser" \
#     MSF_RPC_PASS="msfpass" \
#     MSF_RPC_SSL="true" \
#     MSF_SSL_VERIFY="false" \
#     MSF_CALLBACK_HOST="fqdn.domain.com" \
#     BEEF_SE_ENABLE="false"  \
#     SE_POSH_HOST="fqdn.domain.com" \
#     SE_POSH_PORT="4343" \
#     BEEF_EMAIL_ENABLE="false" \
#     BEEF_EMAIL_TO="none@none.com" \
#     BEEF_EMAIL_FROM="none@none.com" \
#     BEEF_EMAIL_HOST="smtp.none.com" \
#     BEEF_EMAIL_PORT="25" \
#     BEEF_PHISHINGFRENZY_ENABLE="false"

EXPOSE ${TF_VAR_DOCKER_BEEF_PORT}
EXPOSE 6789 61985 61986

COPY ./entrypoint.sh /beef/
ENTRYPOINT ["./entrypoint.sh"]
