ARG VERSION
FROM ruby:${VERSION}

RUN apt-get update && apt-get install sudo -y && \
    git clone https://github.com/beefproject/beef

WORKDIR /beef

ENV GITACTIONS no
ENV TERM xterm
RUN /bin/bash -c "yes | ./install"

COPY ./entrypoint.sh /beef/
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
