FROM ruby:3.2.2

ARG VERSION

RUN apt-get update && apt-get install sudo gcc -y && \
    git clone https://github.com/beefproject/beef
    # git clone --depth 1 --branch v$VERSION https://github.com/beefproject/beef

WORKDIR /beef

ENV GITACTIONS no
ENV TERM xterm
RUN /bin/bash -c "yes | ./install"

COPY ./entrypoint.sh /beef/
ENTRYPOINT ["./entrypoint.sh"]
