
services:
  memcached: # TF_VAR_MEMCACHED_NAME
    image: ${TF_DOMAIN}/${TF_VAR_MEMCACHED_NAME}:${TF_VAR_VERSION_DOCKER_MEMCACHED}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_MEMCACHED_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_MEMCACHED}
    container_name: ${TF_VAR_MEMCACHED_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_MEMCACHED_NAME}:/data
    command: memcached -m 256M
