
services:
  vault: # ${TF_VAR_VAULT_NAME}-relay
    image: ${TF_DOMAIN}/${TF_VAR_VAULT_NAME}:${TF_VAR_VERSION_DOCKER_VAULT}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_VAULT_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_VAULT}
    container_name: ${TF_VAR_VAULT_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_VAULT_PORT_EXT}:${TF_VAR_VAULT_PORT_INT}
    volumes:
      - $HOME/docker/${TF_VAR_VAULT_NAME}:/data
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: 'https://0.0.0.0:${TF_VAR_VAULT_PORT_INT}'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:${TF_VAR_VAULT_PORT_INT}","tls_disable":"1"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: ${TF_VAR_VAULT_TOKEN_ROOT}
      VAULT_TOKEN: ${TF_VAR_VAULT_TOKEN_USER}
    command: server -dev -dev-root-token-id="${TF_VAR_VAULT_TOKEN_ROOT}"
    networks:
      - ${TF_VAR_VAULT_NAME}

networks:
  vault: # ${TF_VAR_VAULT_NAME}
    name: ${TF_VAR_VAULT_NAME}
    driver: bridge