x-shared:
  zammad-service: &zammad-service
    depends_on:
      - ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_MEMCACHED_NAME}
      - ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_POSTGRES_NAME}
      - ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_REDIS_NAME}
    image: ${TF_DOMAIN}/${TF_VAR_ZAMMAD_NAME}:${TF_VAR_VERSION_DOCKER_ZAMMAD}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_ZAMMAD_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_ZAMMAD}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_ZAMMAD_NAME}:/opt/zammad/storage
    environment: &zammad-environment
      MEMCACHE_SERVERS: ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_MEMCACHED_NAME}:${TF_VAR_MEMCACHED_PORT_INT}
      POSTGRESQL_DB: ${TF_VAR_ZAMMAD_NAME}
      POSTGRESQL_HOST: ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_POSTGRES_NAME}
      POSTGRESQL_USER: ${TF_VAR_POSTGRES_USER}
      POSTGRESQL_PASS: ${TF_VAR_POSTGRES_PASSWORD}
      POSTGRESQL_PORT: ${TF_VAR_POSTGRES_PORT_INT}
      REDIS_URL: redis://${TF_VAR_ZAMMAD_NAME}-${TF_VAR_REDIS_NAME}:${TF_VAR_REDIS_PORT_INT}
      # Allow passing in these variables via .env:
      AUTOWIZARD_JSON:
      AUTOWIZARD_RELATIVE_PATH:
      ELASTICSEARCH_ENABLED:
      ELASTICSEARCH_HOST:
      ELASTICSEARCH_PORT:
      ELASTICSEARCH_SCHEMA:
      ELASTICSEARCH_NAMESPACE:
      ELASTICSEARCH_REINDEX:
      ELASTICSEARCH_SSL_VERIFY:
      NGINX_PORT:
      NGINX_SERVER_NAME:
      NGINX_SERVER_SCHEME:
      POSTGRESQL_DB_CREATE:
      POSTGRESQL_OPTIONS:
      RAILS_TRUSTED_PROXIES:
      ZAMMAD_WEB_CONCURRENCY:
      ZAMMAD_SESSION_JOBS:
      ZAMMAD_PROCESS_SCHEDULED:
      ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS:
    networks:
      - ${TF_VAR_ZAMMAD_NAME}

services:
  zammad-railsserver: # ${TF_VAR_ZAMMAD_NAME}-railsserver
    <<: *zammad-service
    container_name: ${TF_VAR_ZAMMAD_NAME}-railsserver
    command: ["zammad-railsserver"]

  zammad-scheduler: # ${TF_VAR_ZAMMAD_NAME}-scheduler
    <<: *zammad-service
    container_name: ${TF_VAR_ZAMMAD_NAME}-scheduler
    command: ["zammad-scheduler"]

  zammad-websocket: # ${TF_VAR_ZAMMAD_NAME}-websocket
    <<: *zammad-service
    container_name: ${TF_VAR_ZAMMAD_NAME}-websocket
    command: ["zammad-websocket"]

  zammad-init: # ${TF_VAR_ZAMMAD_NAME}-init
    <<: *zammad-service
    depends_on:
      - ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_POSTGRES_NAME}
    container_name: ${TF_VAR_ZAMMAD_NAME}-init
    command: ["zammad-init"]
    user: 0:0

  zammad-nginx: # ${TF_VAR_ZAMMAD_NAME}-nginx
    <<: *zammad-service
    depends_on:
      - ${TF_VAR_ZAMMAD_NAME}-railsserver
    container_name: ${TF_VAR_ZAMMAD_NAME}-nginx
    command: ["zammad-nginx"]
    ports:
      - ${TF_VAR_ZAMMAD_PORT_EXT}:${TF_VAR_ZAMMAD_PORT_INT}
    expose:
      - ${TF_VAR_ZAMMAD_PORT_INT}

  zammad-postgres: # ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_POSTGRES_NAME}
    extends:
      service: ${TF_VAR_POSTGRES_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_POSTGRES_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_POSTGRES_NAME}
    volumes:
      - $HOME/docker/${TF_VAR_ZAMMAD_NAME}/${TF_VAR_POSTGRES_NAME}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${TF_VAR_ZAMMAD_NAME}
    networks:
      - ${TF_VAR_ZAMMAD_NAME}

  # zammad-backup: # ${TF_VAR_ZAMMAD_NAME}-backup
  #   depends_on:
  #     - ${TF_VAR_ZAMMAD_NAME}-railsserver
  #     - ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_POSTGRES_NAME}
  #   extends:
  #     service: ${TF_VAR_POSTGRES_NAME}
  #     file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_POSTGRES_NAME}/docker-compose.yaml
  #   container_name: ${TF_VAR_ZAMMAD_NAME}-backup
  #   volumes:
  #     - $HOME/docker/${TF_VAR_ZAMMAD_NAME}/backup:/var/tmp/zammad
  #     - $HOME/docker/${TF_VAR_ZAMMAD_NAME}/backup/storage:/opt/zammad/storage:ro
  #     - ${TF_VAR_PATH_APP}/docker/${TF_VAR_ZAMMAD_NAME}/scripts/backup.sh:/usr/local/bin/backup.sh:ro
  #   environment:
  #     <<: *zammad-environment
  #     BACKUP_TIME: "03:00"
  #     HOLD_DAYS: "10"
  #     TZ: ${TF_VAR_ZAMMAD_TZ}
  #   command: ["zammad-backup"]
  #   entrypoint: /usr/local/bin/backup.sh
  #   networks:
  #     - ${TF_VAR_ZAMMAD_NAME}

  zammad-redis: # ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_REDIS_NAME}
    extends:
      service: ${TF_VAR_REDIS_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_REDIS_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_REDIS_NAME}
    volumes:
      - $HOME/docker/${TF_VAR_ZAMMAD_NAME}/${TF_VAR_REDIS_NAME}:/data
    networks:
      - ${TF_VAR_ZAMMAD_NAME}

  zammad-memcached: # ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_MEMCACHED_NAME}
    extends:
      service: ${TF_VAR_MEMCACHED_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_MEMCACHED_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_MEMCACHED_NAME}
    networks:
      - ${TF_VAR_ZAMMAD_NAME}

  zammad-elasticsearch: # ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_ELASTICSEARCH_NAME}
    extends:
      service: ${TF_VAR_ELASTICSEARCH_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_ELASTICSEARCH_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_ZAMMAD_NAME}-${TF_VAR_ELASTICSEARCH_NAME}
    volumes:
      - $HOME/docker/${TF_VAR_ZAMMAD_NAME}/${TF_VAR_ELASTICSEARCH_NAME}:/usr/share/elasticsearch/data
    networks:
      - ${TF_VAR_ZAMMAD_NAME}

networks:
  zammad: # ${TF_VAR_ZAMMAD_NAME}
    name: ${TF_VAR_ZAMMAD_NAME}
    driver: bridge
