FROM ubuntu:22.04

ARG VERSION

RUN apt-get update && apt-get install -y make gcc curl && \
    curl -sSLo softether-vpnserver.tar.gz https://www.softether-download.com/files/softether/v$VERSION-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v$VERSION-linux-x64-64bit.tar.gz && \
    tar -zxvf softether-vpnserver.tar.gz && \
    rm softether-vpnserver.tar.gz

WORKDIR /vpnserver

RUN make main

ENTRYPOINT ["./vpnserver", "execsvc"]
