version: '3.9'

services:
  twingate: # ${TF_VAR_TWINGATE_NAME}
    image: ${TF_VAR_DOMAIN}/${TF_VAR_TWINGATE_NAME}:${TF_VAR_VERSION_DOCKER_TWINGATE}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_TWINGATE_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_TWINGATE}
    container_name: ${TF_VAR_TWINGATE_NAME}
    restart: unless-stopped
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    environment:
      TENANT_URL: https://$TF_VAR_TWINGATE_TENANT_NETWORK.$TF_VAR_TWINGATE_DOMAIN
      ACCESS_TOKEN: ${TF_VAR_TWINGATE_ACCESS_TOKEN}
      REFRESH_TOKEN: ${TF_VAR_TWINGATE_REFRESH_TOKEN}
      TWINGATE_LABEL_HOSTNAME: ${TF_VAR_TWINGATE_LABEL_HOSTNAME}
