
services:
  nginx: # ${TF_VAR_NGINX_NAME}
    image: ${TF_DOMAIN}/${TF_VAR_NGINX_NAME}:${TF_VAR_VERSION_DOCKER_NGINX}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_NGINX_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_NGINX}
    container_name: ${TF_VAR_NGINX_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_NGINX_PORT_EXT}:${TF_VAR_NGINX_PORT_INT}
    environment:
      NGINX_HOST: ${TF_DOMAIN}
      NGINX_PORT: ${TF_VAR_NGINX_PORT_INT}