version: '3.8'

services:
  redis: # TF_VAR_REDIS_NAME
    image: ${TF_VAR_DOMAIN}/${TF_VAR_REDIS_NAME}:${TF_VAR_VERSION_DOCKER_REDIS}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_REDIS_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_REDIS}
    container_name: ${TF_VAR_REDIS_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_REDIS_NAME}:/data
    # ports:
    #   - ${TF_VAR_REDIS_PORT_EXT}:${TF_VAR_REDIS_PORT_INT}
    command: redis-server --save 20 1 --loglevel warning 
    #--requirepass ${TF_VAR_REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5