version: '3.8'

services:
  prometheus: # TF_VAR_PROMETHEUS_NAME
    image: prom/prometheus:v${TF_VAR_VERSION_DOCKER_PROMETHEUS}
    container_name: ${TF_VAR_PROMETHEUS_NAME}
    restart: unless-stopped
    volumes:
      - ./config/prometheus:/etc/prometheus
      - $HOME/docker/${TF_VAR_PROMETHEUS_NAME}:/prometheus
    # ports:
    #   - ${TF_VAR_PROMETHEUS_PORT_EXT}:${TF_VAR_PROMETHEUS_PORT_INT}
    user: root
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
