
services:
  prometheus: # TF_VAR_PROMETHEUS_NAME
    image: ${TF_VAR_DOMAIN}/${TF_VAR_PROMETHEUS_NAME}:${TF_VAR_VERSION_DOCKER_PROMETHEUS}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_PROMETHEUS_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_PROMETHEUS}
    container_name: ${TF_VAR_PROMETHEUS_NAME}
    restart: unless-stopped
    volumes:
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_PROMETHEUS_NAME}/config/prometheus:/etc/prometheus
      - $HOME/docker/${TF_VAR_PROMETHEUS_NAME}:/prometheus
    # ports:
    #   - ${TF_VAR_PROMETHEUS_PORT_EXT}:${TF_VAR_PROMETHEUS_PORT_INT}
    user: root
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
