version: '3.8'

services:
  sherlock: # ${TF_VAR_SHERLOCK_NAME}
    image: ${TF_VAR_DOMAIN}/${TF_VAR_SHERLOCK_NAME}:${TF_VAR_VERSION_DOCKER_PYTHON}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_SHERLOCK_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_PYTHON}
    container_name: ${TF_VAR_SHERLOCK_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_SHERLOCK_NAME}:/opt/sherlock/results
    stdin_open: true
    tty: true
