ARG VERSION
FROM python:${VERSION}

RUN apt-get update && apt-get install git -y && \
    git clone https://github.com/sherlock-project/sherlock.git

WORKDIR /sherlock

RUN python3 -m pip install -r requirements.txt

WORKDIR /sherlock/sherlock

ENTRYPOINT ["tail", "-f", "/dev/null"]

