
services:
  papercut: # TF_VAR_PAPERCUT_NAME
    image: ${TF_DOMAIN}/${TF_VAR_PAPERCUT_NAME}:${TF_VAR_VERSION_DOCKER_PUTER}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_PAPERCUT_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_PAPERCUT}
    container_name: ${TF_VAR_PAPERCUT_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_PAPERCUT_GUI_PORT_EXT}:${TF_VAR_PAPERCUT_GUI_PORT_INT}
      - ${TF_VAR_PAPERCUT_SMTP_PORT_EXT}:${TF_VAR_PAPERCUT_SMTP_PORT_INT}