version: '3.9'

services:
  phpmyadmin: # TF_VAR_PHPMYADMIN_NAME
    image: ${TF_VAR_DOMAIN}/${TF_VAR_PHPMYADMIN_NAME}:${TF_VAR_VERSION_DOCKER_PHPMYADMIN}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_PHPMYADMIN_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_PHPMYADMIN}
    container_name: ${TF_VAR_PHPMYADMIN_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_PHPMYADMIN_PORT_EXT}:${TF_VAR_PHPMYADMIN_PORT_INT}
    environment:
      - PMA_ARBITRARY=1