version: '3.9'

services:
  filebrowser: # ${TF_VAR_FILEBROWSER_NAME}
    image: ${TF_VAR_DOMAIN}/${TF_VAR_FILEBROWSER_NAME}:${TF_VAR_VERSION_DOCKER_FILEBROWSER}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_FILEBROWSER_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_FILEBROWSER}
    container_name: ${TF_VAR_FILEBROWSER_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_FILEBROWSER_PORT_EXT}:${TF_VAR_FILEBROWSER_PORT_INT}
    volumes:
      - $HOME/docker/${TF_VAR_FILEBROWSER_NAME}/files:/srv
      # - $HOME/docker/filebrowser/filebrowser.db:/database.db
      # - $HOME/docker/filebrowser/filebrowser.json:/.filebrowser.json
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000

