# http://localhost:${TF_VAR_STORMBREAKER_PORT_EXT}/index.php

services:
  storm-breaker: # ${TF_VAR_STORMBREAKER_NAME}
    image: ${TF_VAR_DOMAIN}/${TF_VAR_STORMBREAKER_NAME}:${TF_VAR_VERSION_DOCKER_PYTHON}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_STORMBREAKER_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_PYTHON}
    container_name: ${TF_VAR_STORMBREAKER_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_STORMBREAKER_NAME}/images/:/var/www/html/images
      - $HOME/docker/${TF_VAR_STORMBREAKER_NAME}/sounds/:/var/www/html/sounds
      - $HOME/docker/${TF_VAR_STORMBREAKER_NAME}/log/:/var/www/html/log
    ports:
      - ${TF_VAR_STORMBREAKER_PORT_EXT}:${TF_VAR_STORMBREAKER_PORT_INT}
    environment:
      - USERNAME=${TF_VAR_STORMBREAKER_USER}
      - PASSWORD=${TF_VAR_STORMBREAKER_PASSWORD}
      - NGROK_API_KEY=${TF_VAR_STORMBREAKER_NGROK_API_KEY}
