# user/password: guacadmin/guacadmin

version: "3.8"

services:
  guacamole-mysql: # ${TF_VAR_GUACAMOLE_NAME}-${TF_VAR_MYSQL_NAME}
    extends:
      service: ${TF_VAR_MYSQL_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_MYSQL_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_GUACAMOLE_NAME}-${TF_VAR_MYSQL_NAME}
    volumes:
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_GUACAMOLE_NAME}/config/${TF_VAR_MYSQL_NAME}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - $HOME/docker/${TF_VAR_GUACAMOLE_NAME}/${TF_VAR_MYSQL_NAME}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${TF_VAR_GUACAMOLE_NAME}
    networks:
      - ${TF_VAR_GUACAMOLE_NAME}

  guacd:
    image: guacamole/guacd:${TF_VAR_VERSION_DOCKER_GUACD}
    container_name: ${TF_VAR_GUACD_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_GUACAMOLE_NAME}/${TF_VAR_GUACD_NAME}/config:/config
      - $HOME/docker/${TF_VAR_GUACAMOLE_NAME}/${TF_VAR_GUACD_NAME}/drive:/drive:rw
      - $HOME/docker/${TF_VAR_GUACAMOLE_NAME}/${TF_VAR_GUACD_NAME}/record:/record:rw
    # ports:
    #   - ${TF_VAR_GUACD_PORT_EXT}:${TF_VAR_GUACD_PORT_INT}
    networks:
      - ${TF_VAR_GUACAMOLE_NAME}

  guacamole: # ${TF_VAR_GUACAMOLE_NAME}
    depends_on:
      - ${TF_VAR_GUACD_NAME}
      - ${TF_VAR_GUACAMOLE_NAME}-${TF_VAR_MYSQL_NAME}
    image: guacamole/guacamole:${TF_VAR_VERSION_DOCKER_GUACAMOLE}
    container_name: ${TF_VAR_GUACAMOLE_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_GUACAMOLE_NAME}/initdb:/data
    ports:
      - ${TF_VAR_GUACAMOLE_PORT_EXT}:${TF_VAR_GUACAMOLE_PORT_INT}
    environment:
      GUACD_HOSTNAME: ${TF_VAR_GUACD_NAME}
      GUACD_PORT: ${TF_VAR_GUACD_PORT_INT}
      MYSQL_HOSTNAME: ${TF_VAR_GUACAMOLE_NAME}-${TF_VAR_MYSQL_NAME}
      MYSQL_DATABASE: ${TF_VAR_GUACAMOLE_NAME}
      MYSQL_USER: ${TF_VAR_MYSQL_USER}
      MYSQL_PASSWORD: ${TF_VAR_MYSQL_PASSWORD}
    links:
      - ${TF_VAR_GUACD_NAME}
      - ${TF_VAR_GUACAMOLE_NAME}-${TF_VAR_MYSQL_NAME}
    networks:
      - ${TF_VAR_GUACAMOLE_NAME}

networks:
  guacamole: # ${TF_VAR_GUACAMOLE_NAME}
    name: ${TF_VAR_GUACAMOLE_NAME}
    driver: bridge
