
services:
  listmonk-postgres: # ${TF_VAR_LISTMONK_NAME}-${TF_VAR_POSTGRES_NAME}
    extends:
      service: ${TF_VAR_POSTGRES_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_POSTGRES_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_LISTMONK_NAME}-${TF_VAR_POSTGRES_NAME}
    volumes:
      - $HOME/docker/${TF_VAR_LISTMONK_NAME}/${TF_VAR_POSTGRES_NAME}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TF_VAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TF_VAR_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TF_VAR_LISTMONK_NAME}
    networks:
      - ${TF_VAR_LISTMONK_NAME}

  listmonk: # ${TF_VAR_LISTMONK_NAME}
    depends_on:
      listmonk-postgres: # ${TF_VAR_LISTMONK_NAME}-${TF_VAR_POSTGRES_NAME}
        condition: service_healthy
    image: ${TF_DOMAIN}/${TF_VAR_LISTMONK_NAME}:${TF_VAR_VERSION_DOCKER_LISTMONK}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_LISTMONK_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_LISTMONK}
    container_name: ${TF_VAR_LISTMONK_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_LISTMONK_PORT_EXT}:${TF_VAR_LISTMONK_PORT_INT}
    environment:
      - TZ=Etc/UTC
      - LISTMONK_NAME=${TF_VAR_LISTMONK_NAME}
      - LISTMONK_USER=${TF_VAR_LISTMONK_USER}
      - LISTMONK_PASSWORD=${TF_VAR_LISTMONK_PASSWORD}
      - LISTMONK_PORT_INT=${TF_VAR_LISTMONK_PORT_INT}
      - POSTGRES_NAME=${TF_VAR_POSTGRES_NAME}
      - POSTGRES_USER=${TF_VAR_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TF_VAR_POSTGRES_PASSWORD}
      - POSTGRES_PORT_INT=${TF_VAR_POSTGRES_PORT_INT}
    networks:
      - ${TF_VAR_LISTMONK_NAME}

networks:
  listmonk: # ${TF_VAR_LISTMONK_NAME}
    name: ${TF_VAR_LISTMONK_NAME}
    driver: bridge
