#!/bin/bash

${TF_VAR_PATH_APP}/docker/${TF_VAR_BEEF_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_CASSANDRA_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_CHATGPT_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_CODESERVER_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_DASHY_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_ELASTICSEARCH_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_FILEBROWSER_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_FREESCOUT_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_GITLAB_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_GRAFANA_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_GUACAMOLE_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_HACK_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_HARBOR_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_JELLYFIN_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_JENKINS_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_KALI_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_KEYCLOAK_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_KIBANA_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_KUTT_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_LISTMONK_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_MARIADB_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_MEMCACHED_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_MONGODB_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_MYSQL_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_NPM_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_OLLAMA_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_PAPERCUT_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_PGADMIN_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_PHONEINFOGA_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_PHPMYADMIN_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_PIHOLE_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_POSTGRES_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_PROMETHEUS_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_PUTER_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_RABBITMQ_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_REDIS_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_REDISCOMMANDER_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_RUSTDESK_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_SEARXNG_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_SHERLOCK_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_SOFTETHER_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_STIRLINGPDF_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_STORMBREAKER_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_TRAEFIK_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_TWINGATE_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_UBUNTU_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_UPTIMEKUMA_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_VAULT_NAME}/recreate.sh
${TF_VAR_PATH_APP}/docker/${TF_VAR_VAULTWARDEN_NAME}/recreate.sh
