version: '3.8'

services:
  jenkins: # ${TF_VAR_JENKINS_NAME}
    image: ${TF_VAR_DOMAIN}/${TF_VAR_JENKINS_NAME}:${TF_VAR_VERSION_DOCKER_JENKINS}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_JENKINS_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_JENKINS}
    container_name: ${TF_VAR_JENKINS_NAME}
    restart: unless-stopped
    ports:
      - ${TF_VAR_JENKINS_PORT_EXT}:${TF_VAR_JENKINS_PORT_INT}
      - ${TF_VAR_JENKINS_PORT_EXT_50000}:${TF_VAR_JENKINS_PORT_INT_50000}
    volumes:
      - $HOME/docker/jenkins:/var/jenkins_home
      - $HOME/docker/jenkins/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=${TF_VAR_JENKINS_USER} --argumentsRealm.passwd.admin=${TF_VAR_JENKINS_PASSWORD} --argumentsRealm.roles.admin=admin
    privileged: true
    user: root
