version: "3.8"

services:
  vaultwarden-postgres: # ${TF_VAR_VAULTWARDEN_NAME}-${TF_VAR_POSTGRES_NAME}
    extends:
      service: ${TF_VAR_POSTGRES_NAME}
      file: ${TF_VAR_PATH_APP}/docker/${TF_VAR_POSTGRES_NAME}/docker-compose.yaml
    container_name: ${TF_VAR_VAULTWARDEN_NAME}-${TF_VAR_POSTGRES_NAME}
    volumes:
      - $HOME/docker/${TF_VAR_VAULTWARDEN_NAME}/${TF_VAR_POSTGRES_NAME}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${TF_VAR_VAULTWARDEN_NAME}
    networks:
      - ${TF_VAR_VAULTWARDEN_NAME}

  vaultwarden: # ${TF_VAR_VAULTWARDEN_NAME}
    depends_on:
      - ${TF_VAR_VAULTWARDEN_NAME}-${TF_VAR_POSTGRES_NAME}
    image: vaultwarden/server:${TF_VAR_VERSION_DOCKER_VAULTWARDEN}
    container_name: ${TF_VAR_VAULTWARDEN_NAME}
    restart: unless-stopped
    volumes:
      - $HOME/docker/${TF_VAR_VAULTWARDEN_NAME}/:/data/
    ports:
      - ${TF_VAR_VAULTWARDEN_PORT_EXT}:${TF_VAR_VAULTWARDEN_PORT_INT}
    environment:
      - DATABASE_URL=postgresql://${TF_VAR_POSTGRES_USER}:${TF_VAR_POSTGRES_PASSWORD}@${TF_VAR_VAULTWARDEN_NAME}-${TF_VAR_POSTGRES_NAME}:${TF_VAR_POSTGRES_PORT_INT}/${TF_VAR_VAULTWARDEN_NAME}
      - ADMIN_TOKEN=${TF_VAR_VAULTWARDEN_ADMIN_TOKEN}
      - DOMAIN=https://${TF_VAR_VAULTWARDEN_DOMAIN}
      - SMTP_HOST=${TF_VAR_SMTP_HOST}
      - SMTP_FROM=${TF_VAR_VAULTWARDEN_NAME}@${TF_VAR_DOMAIN}
      - SMTP_FROM_NAME=${TF_VAR_VAULTWARDEN_NAME}
      - SMTP_SECURITY=${TF_VAR_SMTP_SECURITY}
      - SMTP_PORT=${TF_VAR_SMTP_PORT}
      - SMTP_USERNAME=${TF_VAR_SMTP_USERNAME}
      - SMTP_PASSWORD=${TF_VAR_SMTP_PASSWORD}
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM=Login
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - INVITATION_ORG_NAME=${TF_VAR_VAULTWARDEN_NAME}
      - INVITATIONS_ALLOWED=false
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_DOMAINS_WHITELIST=${TF_VAR_VAULTWARDEN_DOMAIN}
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=1
      - EMERGENCY_ACCESS_ALLOWED=false
      - SHOW_PASSWORD_HINT=false
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
    networks:
      - ${TF_VAR_VAULTWARDEN_NAME}

networks:
  vaultwarden: # ${TF_VAR_VAULTWARDEN_NAME}
    name: ${TF_VAR_VAULTWARDEN_NAME}
    driver: bridge
