# default user/pass: admin/admin


services:
  grafana: # ${TF_VAR_GRAFANA_NAME}
    image: ${TF_VAR_DOMAIN}/${TF_VAR_GRAFANA_NAME}:${TF_VAR_VERSION_DOCKER_GRAFANA}
    build:
      context: .
      dockerfile: ${TF_VAR_PATH_APP}/docker/${TF_VAR_GRAFANA_NAME}/dockerfile
      args:
        VERSION: ${TF_VAR_VERSION_DOCKER_GRAFANA}
    container_name: ${TF_VAR_GRAFANA_NAME}
    restart: unless-stopped
    volumes:
      - ${TF_VAR_PATH_APP}/docker/${TF_VAR_GRAFANA_NAME}/config/${TF_VAR_GRAFANA_NAME}:/etc/grafana/provisioning/datasources
      - $HOME/docker/${TF_VAR_GRAFANA_NAME}:/var/lib/grafana
    ports:
      - ${TF_VAR_GRAFANA_PORT_EXT}:${TF_VAR_GRAFANA_PORT_INT}
    user: root