#!/bin/bash

# --------------------------------------------------
# ✏️ INPUT ➡️ ~/.bashrc
# --------------------------------------------------
PARAM_PREFIX=$1
PARAM_PROVIDER=$2
PARAM_ENVIRONMENT=$3
PARAM_REGION=$4

test -z $PARAM_PREFIX      && PARAM_PREFIX=$TF_VAR_PREFIX_NONE
test -z $PARAM_PROVIDER    && PARAM_PROVIDER=$TF_VAR_PROVIDER_KIND
test -z $PARAM_ENVIRONMENT && PARAM_ENVIRONMENT=$TF_VAR_ENVIRONMENT_PRD
test -z $PARAM_REGION      && PARAM_REGION=$TF_VAR_REGION_NONE

# --------------------------------------------------
# 🏢 WORKSPACE
# --------------------------------------------------
POINT_PREFIX=$PARAM_PREFIX
STRIP_PREFIX=$PARAM_PREFIX
POINT_ENVIRONMENT=""
STRIP_REGION=""

if [ "$PARAM_PREFIX" != "$TF_VAR_PREFIX_NONE" ]; then
   POINT_PREFIX=$POINT_PREFIX.
   STRIP_PREFIX=$STRIP_PREFIX-
fi
if [ "$PARAM_ENVIRONMENT" != "$TF_VAR_ENVIRONMENT_PRD" ]; then
   POINT_ENVIRONMENT=$PARAM_ENVIRONMENT.
fi
if [ "$PARAM_REGION" != "$TF_VAR_REGION_NONE" ]; then
   STRIP_REGION=$PARAM_REGION-
fi

export TF_VAR_PREFIX=$PARAM_PREFIX
export TF_VAR_PROVIDER=$PARAM_PROVIDER
export TF_VAR_ENVIRONMENT=$PARAM_ENVIRONMENT
export TF_VAR_REGION=$PARAM_REGION
export TF_DOMAIN=$POINT_PREFIX$POINT_ENVIRONMENT$TF_VAR_HOST
export TF_CLUSTERNAME=$STRIP_PREFIX$STRIP_REGION$PARAM_ENVIRONMENT
export TF_WORKSPACE=$TF_VAR_PROVIDER-$TF_VAR_CLUSTERNAME

echo " PREFIX:       " $TF_VAR_PREFIX
echo " PROVIDER:     " $TF_VAR_PROVIDER
echo " ENVIRONMENT:  " $TF_VAR_ENVIRONMENT
echo " REGION:       " $TF_VAR_REGION
echo " DOMAIN:       " $TF_VAR_DOMAIN
echo " CLUSTERNAME:  " $TF_VAR_CLUSTERNAME
echo " WORKSPACE:    " $TF_WORKSPACE


